### PR TITLE
Added workaround for cpanfiles versioned for carton

### PR DESCRIPTION
**Pull request by PaulGWebster**
As the title says I have no idea if it will cause problems elsewhere though!

### CODE REVIEW

**Comment by karenetheridge** [comment]
What usecases are you adding support for? The format of the cpanfile used by this plugin should already be compatible with carton.  Perhaps some tests would offer enlightenment?

**Comment by Leont** [comment]
This looks wrong to me TBH (though I'm not 100% sure of that).

Probably you should start with adding a tests that shows this problem.

**Comment by miyagawa** [comment]
This seems to me a wrong place to fix the issue, and if anything you should fix this in the MakeMaker dzil plugin to remove `==` if that's what you want.

**Comment by PaulGWebster** [comment]
Hi there of course, though it is really very simple to test; all that is required is a cpanfile that would be compatible with carton, here is mine and the one that caused me to create this terrible patch:

```
$ cat cpanfile
requires 'Mojolicious','== 9.27'
```

This will work perfectly well with carton but when you attempt to use it with Dist::Zilla::Plugin::Prereqs::FromCPANfile

you wll get the following:

```
paul.webster@PAUL-PC-RGB:~/personal/ptr.bond/Author-Daemon-Site-Ptr-Bond$ dzil build
[DZ] beginning to build Author-Daemon-Site-Ptr-Bond
[Git::NextVersion] Bumping version from 0.005 to 0.006
[Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[MakeMaker] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): Mojolicious == 9.27
[MakeMaker] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): Mojolicious == 9.27 at inline delegation in Dist::Zilla::Plugin::MakeMaker for logger->log_fatal (attribute declared in /home/paul.webster/perl5/lib/perl5/Dist/Zilla/Role/Plugin.pm at line 67) line 18.
```

**Comment by miyagawa** [comment]
@PaulGWebster as I noted in #6 `dzil build` works fine if I use a builder plugin that's not MakeMaker i.e. ModuleBuild, which leads me to think this is a problem specific to the MakeMaker.

**Comment by karenetheridge** [comment]
> [MakeMaker] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): Mojolicious == 9.27

And what happens when you do

```
[MakeMaker]
eumm_version = 7.1101
```
?

**Comment by PaulGWebster** [comment]
Then it works \o/


I assumed it would automatically use the latest version, thank you for that!

On 10 October 2022 03:07:21 (+01:00), Karen Etheridge wrote:



[MakeMaker] found version range in runtime prerequisites, which ExtUtils::MakeMaker cannot parse (must specify eumm_version of at least 7.1101): Mojolicious == 9.27

And what happens when you do

[MakeMaker]
eumm_version = 7.1101


?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.


-- 
-- Thank you for time
-- Paul G Webster

**Pull request closed without merging**
